# Generated by Django 5.1.1 on 2024-10-31 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('diagnose_id', models.AutoField(primary_key=True, serialize=False)),
                ('complete_diagnosis', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField()),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.doctor'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('insurance_info', models.CharField(max_length=100)),
                ('personal_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('contact_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='diagnose.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('left_fundus', models.ImageField(blank=True, null=True, upload_to='fundus_images/')),
                ('right_fundus', models.ImageField(blank=True, null=True, upload_to='fundus_images/')),
                ('left_diagnostic', models.CharField(max_length=255)),
                ('right_diagnostic', models.CharField(max_length=255)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('diagnose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnose.diagnose')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnose.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.patient'),
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=100)),
                ('daily_activities', models.TextField()),
                ('surgical_intervention', models.TextField(blank=True, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnose.medicaldata')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'doctor', 'appointment_datetime')},
        ),
    ]
