# Generated by Django 5.1.1 on 2024-10-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='appointment_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnose.appointment'),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='diagnose',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnose.diagnose'),
        ),
    ]
